name: publish
on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    name: Building and publishing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
      - name: build docker image
        run: |
          docker build -t ghcr.io/sonac/hilmm_client/hilmm_client:latest .
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push to github packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: sonac/hilmm_client/hilmm_client
          tag_with_ref: true
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USER }}
          envs: GITHUB_USERNAME
          script: |
            cd apps
            docker compose down
            cat gh_token | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
            docker pull ghcr.io/sonac/hilmm_client/hilmm_client:latest
            docker compose up -d
